SELECT L.ACCESSION
FROM APP.COMPOUND_DATA L
LEFT JOIN APP.COMPOUND_SYNONYM I ON L.CPD_NAME = I.CPD_NAME
WHERE I.ACCESSION IS NULL

select * from APP.COMPOUND_SYNONYM where
accession = '187353' and
CPD_NAME like '%Â%'

select * from APP.COMPOUND_DATA where accession = 'AAAA'

select * from app.ms_library_component c where c.target_id = 'TGT_7fb9989b-0389-4723-85b2-8eb18a2d775f'

update app.ms_library_component c set c.cid = 'HMDB0002428', c.name = 'TEREPHTHALIC ACID' where c.target_id = 'TGT_1e4a9c15-d66a-4cc9-94ec-8c1fbbcf053d'


select * from app.compound_data d where d.accession = '644280'

select count(*) from APP.COMPOUND_SYNONYM

---------------------------------------------------------------------
--	Convert RT for LC10 instrument
---------------------------------------------------------------------

--	Positive mode

--	CPDLIB_5d592e3e-cf12-4542-b33c-5d554d32a176	POS LC10

UPDATE APP.MS_LIBRARY_COMPONENT
SET RT_MIN = 0, RT_MAX = 0
WHERE TARGET_ID IN (
SELECT DISTINCT TARGET_ID FROM APP.MS_LIBRARY_KEY WHERE LIBRARY_ID = 'CPDLIB_5d592e3e-cf12-4542-b33c-5d554d32a176')

--	Negative mode

--CPDLIB_6031a610-3c74-4e8a-b8ec-2fd581f8fdf4	NEG LC10




SELECT D.CHEMICAL_FORMULA, D.EXACT_MASS, D.CPD_NAME, D.ACCESSION
FROM APP.MS_LIBRARY_COMPONENT C,
APP.COMPOUND_DATA D
WHERE C.TARGET_ID IN (
SELECT DISTINCT TARGET_ID FROM APP.MS_LIBRARY_KEY WHERE LIBRARY_ID = 'CPDLIB_5d592e3e-cf12-4542-b33c-5d554d32a176')
AND C.CID = D.ACCESSION

-- MS component adducts table
CREATE TABLE APP.MS_LIBRARY_COMPONENNT_ADDUCT (
		TARGET_ID VARCHAR(50) NOT NULL,
		ADDUCT VARCHAR(20) NOT NULL
	);

CREATE INDEX MSL_CA_TGT_IDX ON APP.MS_LIBRARY_COMPONENNT_ADDUCT (TARGET_ID ASC);
CREATE INDEX MSL_CA_ADCT_IDX ON APP.MS_LIBRARY_COMPONENNT_ADDUCT (ADDUCT ASC);

ALTER TABLE APP.MS_LIBRARY_PEAK ADD CONSTRAINT MSL_CA_TARGET_FK FOREIGN KEY (TARGET_ID)
	REFERENCES APP.MS_LIBRARY_COMPONENT (TARGET_ID)
	ON DELETE CASCADE;

ALTER TABLE APP.MS_LIBRARY_PEAK ADD CONSTRAINT MSL_CA_ADDUCT_FK FOREIGN KEY (ADDUCT)
	REFERENCES APP.CHEM_MOD (MOD_NAME)
	ON DELETE CASCADE;

INSERT INTO APP.MS_LIBRARY_COMPONENNT_ADDUCT
SELECT DISTINCT P.TARGET_ID, P.ADDUCT FROM APP.MS_LIBRARY_PEAK P

--
SELECT C.*
FROM APP.COMPOUND_SYNONYM C,
APP.COMPOUND_DATA D
WHERE D.SOURCE_DATABASE='PubChem'
AND C.ACCESSION = D.ACCESSION













